# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: check-news-inpe

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 7 * * *"
  workflow_dispatch:
jobs:  
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Setting up
        uses: actions/checkout@v3
      - name: setting up requirements
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        env:
          KEYWORDS: ${{ secrets.KEYWORDS }}
          KEY: ${{ secrets.KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
        run: python main.py 
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "new news from today"
          git push
